import { getCurrentUser } from '@/utilities/getCurrentUser'
import { getPayload } from 'payload'
import config from '@payload-config'
import { redirect } from 'next/navigation'
import Link from 'next/link'
import { Users, Dumbbell, CalendarDays, ArrowUpRight } from 'lucide-react'
import { PortalShell, PageHeading, EmptyState, StatusPill } from '@/components/kast/PortalShell'
import { membershipLabel } from '@/components/kast/format'
import CreateLidForm from './CreateLidForm'
import LidActions from './LidActions'
export const metadata={title:'Ledenbeheer'}
export default async function MedewerkerPage(){
  const user=await getCurrentUser();if(!user)redirect('/login');if(user.role!=='medewerker'&&user.role!=='admin')redirect('/dashboard')
  const payload=await getPayload({config})
  const [members,plans,courses,coaches]=await Promise.all([payload.find({collection:'leden',limit:100,depth:1,user,overrideAccess:false}),payload.find({collection:'abonnementen',where:{status:{equals:'Actief'}},limit:100,user,overrideAccess:false}),payload.find({collection:'cursussen',limit:100,user,overrideAccess:false}),payload.find({collection:'coaches',limit:100,user,overrideAccess:false})])
  return <PortalShell name={user.name} staff><PageHeading eyebrow="ACHTER DE BALIE" title="Een club vol mensen." description="Beheer leden en houd het aanbod van De Kast in beweging." action={<a href="#nieuw-lid" className="button button-dark button-small">Nieuw lid<ArrowUpRight size={16}/></a>}/><div className="stat-grid">{[{label:'Leden',count:members.totalDocs,icon:Users},{label:'Cursussen',count:courses.totalDocs,icon:CalendarDays},{label:'Coaches',count:coaches.totalDocs,icon:Dumbbell}].map(({label,count,icon:Icon})=><div className="stat-card" key={label}><span>{label}<Icon size={18}/></span><strong>{count}</strong></div>)}</div><div className="dashboard-grid"><section className="content-panel"><div className="panel-top"><h2>Onze leden</h2><Link href="/admin/collections/leden" className="text-link">Uitgebreid beheer<ArrowUpRight size={14}/></Link></div><div className="member-list">{members.docs.length?members.docs.map(member=><article className="member-row" key={member.id}><div className="panel-top"><strong>{member.naam}</strong><StatusPill value={member.status}/></div><p>{member.email}</p><p>{membershipLabel(typeof member.abonnement==='object'?member.abonnement?.type:null)}</p><LidActions lid={member}/></article>):<EmptyState title="Nog geen leden" description="Maak rechts het eerste ledenaccount aan."/>}</div>{members.totalDocs>100&&<p className="catalog-subtitle">De eerste 100 leden worden getoond. Open uitgebreid beheer voor alle leden.</p>}</section><div><section className="content-panel" id="nieuw-lid"><div className="panel-top"><h2>Een nieuw gezicht</h2><Users size={18}/></div><CreateLidForm abonnementen={plans.docs}/></section><section className="content-panel"><div className="panel-top"><h2>Het sportaanbod</h2><Link href="/admin" className="text-link">Beheren<ArrowUpRight size={14}/></Link></div>{courses.docs.map(course=><div className="booking-row" key={course.id}><div className="booking-detail"><strong>{course.naam}</strong><p>{course.beschikbareMomenten?.length||0} cursusmomenten</p></div><StatusPill value={course.status}/></div>)}{coaches.docs.map(coach=><div className="booking-row" key={'coach'+coach.id}><div className="booking-detail"><strong>{coach.naam}</strong><p>{coach.specialisatie}</p></div><StatusPill value={coach.status}/></div>)}{!courses.docs.length&&!coaches.docs.length&&<EmptyState title="Maak ruimte voor sport" description="Voeg cursussen en coaches toe via de beheeromgeving."/>}</section><Link className="text-link" href="/admin/collections/toegangspogingen">Alle toegangspogingen bekijken<ArrowUpRight size={15}/></Link></div></div></PortalShell>
}
