'use client'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowUpRight } from 'lucide-react'
import { membershipLabel } from '@/components/kast/format'
type Plan={id:number;type:string;heeftCursusAddendum?:boolean|null;status:string}
export default function RegisterForm() {
  const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[plan,setPlan]=useState(''),[plans,setPlans]=useState<Plan[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[fetching,setFetching]=useState(true)
  const router=useRouter()
  useEffect(()=>{let active=true;async function load(){try {const res=await fetch('/api/abonnementen?where[status][equals]=Actief&limit=100');if(!res.ok)throw new Error('Abonnementen kunnen niet worden geladen. Probeer het later opnieuw.');const data=await res.json();if(active){setPlans(data.docs||[]);setPlan(data.docs?.[0]?String(data.docs[0].id):'')}}catch(err){if(active)setError(err instanceof Error?err.message:'Abonnementen laden mislukt.')}finally{if(active)setFetching(false)}}void load();return()=>{active=false}},[])
  async function onSubmit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');try{const res=await fetch('/api/register-lid',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,password,abonnementId:Number(plan)})});const data=await res.json();if(!res.ok)throw new Error(res.status>=500?'Aanmelden lukt nu niet. Probeer het later opnieuw.':data.message||'Controleer je gegevens en probeer opnieuw.');const login=await fetch('/api/users/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!login.ok){router.push('/login');return}router.push('/dashboard');router.refresh()}catch(err){setError(err instanceof Error?err.message:'Geen verbinding. Probeer het opnieuw.')}finally{setLoading(false)}}
  return <form className="kast-form" onSubmit={onSubmit}><div className="field"><label htmlFor="register-name">Je naam</label><input id="register-name" autoComplete="name" placeholder="Voor- en achternaam" value={name} onChange={e=>setName(e.target.value)} required/></div><div className="field"><label htmlFor="register-email">E-mailadres</label><input id="register-email" type="email" autoComplete="email" placeholder="jij@voorbeeld.nl" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><label htmlFor="register-password">Kies een wachtwoord</label><input id="register-password" type="password" autoComplete="new-password" placeholder="Je nieuwe wachtwoord" value={password} onChange={e=>setPassword(e.target.value)} required/></div><div className="field"><label htmlFor="register-plan">Jouw abonnement</label><select id="register-plan" value={plan} onChange={e=>setPlan(e.target.value)} disabled={fetching||!plans.length} required>{!plans.length&&<option value="">{fetching?'Abonnementen laden...':'Geen abonnementen beschikbaar'}</option>}{plans.map(a=><option key={a.id} value={a.id}>{membershipLabel(a.type)}{a.heeftCursusAddendum?' + cursussen':''}</option>)}</select><small>{!fetching&&!plans.length?'Er zijn momenteel geen abonnementen beschikbaar. Neem contact op met de balie.':'Met cursusrecht kun je naast fitness ook cursusmomenten boeken.'}</small></div>{error&&<p className="feedback feedback-error" role="alert">{error}</p>}<button className="button button-dark button-full" disabled={loading||fetching||!plan}>{loading?'Account aanmaken...':'Word lid van De Kast'}<ArrowUpRight size={17}/></button></form>
}
