/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-sqlite'
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
  type AnySQLiteColumn,
} from '@payloadcms/db-sqlite/drizzle/sqlite-core'
import { sql, relations } from '@payloadcms/db-sqlite/drizzle'

export const users_sessions = sqliteTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    expiresAt: text('expires_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = sqliteTable(
  'users',
  {
    id: integer('id').primaryKey(),
    name: text('name').notNull(),
    role: text('role', { enum: ['lid', 'medewerker', 'coach', 'admin'] })
      .notNull()
      .default('lid'),
    lid: integer('lid_id').references(() => leden.id, {
      onDelete: 'set null',
    }),
    medewerker: integer('medewerker_id').references(() => medewerkers.id, {
      onDelete: 'set null',
    }),
    coach: integer('coach_id').references(() => coaches.id, {
      onDelete: 'set null',
    }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text('email').notNull(),
    resetPasswordToken: text('reset_password_token'),
    resetPasswordExpiration: text('reset_password_expiration').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text('salt'),
    hash: text('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: text('lock_until').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('users_lid_idx').on(columns.lid),
    index('users_medewerker_idx').on(columns.medewerker),
    index('users_coach_idx').on(columns.coach),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = sqliteTable(
  'media',
  {
    id: integer('id').primaryKey(),
    alt: text('alt'),
    caption: text('caption', { mode: 'json' }),
    folder: integer('folder_id').references(() => payload_folders.id, {
      onDelete: 'set null',
    }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text('url'),
    thumbnailURL: text('thumbnail_u_r_l'),
    filename: text('filename'),
    mimeType: text('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
    sizes_thumbnail_url: text('sizes_thumbnail_url'),
    sizes_thumbnail_width: numeric('sizes_thumbnail_width', { mode: 'number' }),
    sizes_thumbnail_height: numeric('sizes_thumbnail_height', { mode: 'number' }),
    sizes_thumbnail_mimeType: text('sizes_thumbnail_mime_type'),
    sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize', { mode: 'number' }),
    sizes_thumbnail_filename: text('sizes_thumbnail_filename'),
    sizes_square_url: text('sizes_square_url'),
    sizes_square_width: numeric('sizes_square_width', { mode: 'number' }),
    sizes_square_height: numeric('sizes_square_height', { mode: 'number' }),
    sizes_square_mimeType: text('sizes_square_mime_type'),
    sizes_square_filesize: numeric('sizes_square_filesize', { mode: 'number' }),
    sizes_square_filename: text('sizes_square_filename'),
    sizes_small_url: text('sizes_small_url'),
    sizes_small_width: numeric('sizes_small_width', { mode: 'number' }),
    sizes_small_height: numeric('sizes_small_height', { mode: 'number' }),
    sizes_small_mimeType: text('sizes_small_mime_type'),
    sizes_small_filesize: numeric('sizes_small_filesize', { mode: 'number' }),
    sizes_small_filename: text('sizes_small_filename'),
    sizes_medium_url: text('sizes_medium_url'),
    sizes_medium_width: numeric('sizes_medium_width', { mode: 'number' }),
    sizes_medium_height: numeric('sizes_medium_height', { mode: 'number' }),
    sizes_medium_mimeType: text('sizes_medium_mime_type'),
    sizes_medium_filesize: numeric('sizes_medium_filesize', { mode: 'number' }),
    sizes_medium_filename: text('sizes_medium_filename'),
    sizes_large_url: text('sizes_large_url'),
    sizes_large_width: numeric('sizes_large_width', { mode: 'number' }),
    sizes_large_height: numeric('sizes_large_height', { mode: 'number' }),
    sizes_large_mimeType: text('sizes_large_mime_type'),
    sizes_large_filesize: numeric('sizes_large_filesize', { mode: 'number' }),
    sizes_large_filename: text('sizes_large_filename'),
    sizes_xlarge_url: text('sizes_xlarge_url'),
    sizes_xlarge_width: numeric('sizes_xlarge_width', { mode: 'number' }),
    sizes_xlarge_height: numeric('sizes_xlarge_height', { mode: 'number' }),
    sizes_xlarge_mimeType: text('sizes_xlarge_mime_type'),
    sizes_xlarge_filesize: numeric('sizes_xlarge_filesize', { mode: 'number' }),
    sizes_xlarge_filename: text('sizes_xlarge_filename'),
    sizes_og_url: text('sizes_og_url'),
    sizes_og_width: numeric('sizes_og_width', { mode: 'number' }),
    sizes_og_height: numeric('sizes_og_height', { mode: 'number' }),
    sizes_og_mimeType: text('sizes_og_mime_type'),
    sizes_og_filesize: numeric('sizes_og_filesize', { mode: 'number' }),
    sizes_og_filename: text('sizes_og_filename'),
  },
  (columns) => [
    index('media_folder_idx').on(columns.folder),
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
    index('media_sizes_thumbnail_sizes_thumbnail_filename_idx').on(
      columns.sizes_thumbnail_filename,
    ),
    index('media_sizes_square_sizes_square_filename_idx').on(columns.sizes_square_filename),
    index('media_sizes_small_sizes_small_filename_idx').on(columns.sizes_small_filename),
    index('media_sizes_medium_sizes_medium_filename_idx').on(columns.sizes_medium_filename),
    index('media_sizes_large_sizes_large_filename_idx').on(columns.sizes_large_filename),
    index('media_sizes_xlarge_sizes_xlarge_filename_idx').on(columns.sizes_xlarge_filename),
    index('media_sizes_og_sizes_og_filename_idx').on(columns.sizes_og_filename),
  ],
)

export const leden = sqliteTable(
  'leden',
  {
    id: integer('id').primaryKey(),
    naam: text('naam').notNull(),
    email: text('email').notNull(),
    status: text('status', { enum: ['Actief', 'Geannuleerd', 'Inactief', 'Bevestigd'] })
      .notNull()
      .default('Actief'),
    abonnement: integer('abonnement_id').references(() => abonnementen.id, {
      onDelete: 'set null',
    }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex('leden_email_idx').on(columns.email),
    index('leden_abonnement_idx').on(columns.abonnement),
    index('leden_updated_at_idx').on(columns.updatedAt),
    index('leden_created_at_idx').on(columns.createdAt),
  ],
)

export const abonnementen = sqliteTable(
  'abonnementen',
  {
    id: integer('id').primaryKey(),
    type: text('type', {
      enum: ['EenKeerPerWeek', 'TweeKeerPerWeek', 'Onbeperkt', 'CursusAddendum'],
    }).notNull(),
    status: text('status', { enum: ['Actief', 'Geannuleerd', 'Inactief', 'Bevestigd'] })
      .notNull()
      .default('Actief'),
    startDatum: text('start_datum')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    eindDatum: text('eind_datum').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    bezoekenDezeWeek: numeric('bezoeken_deze_week', { mode: 'number' }).notNull().default(0),
    heeftCursusAddendum: integer('heeft_cursus_addendum', { mode: 'boolean' }).default(false),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('abonnementen_updated_at_idx').on(columns.updatedAt),
    index('abonnementen_created_at_idx').on(columns.createdAt),
  ],
)

export const coaches = sqliteTable(
  'coaches',
  {
    id: integer('id').primaryKey(),
    naam: text('naam').notNull(),
    email: text('email').notNull(),
    specialisatie: text('specialisatie').notNull(),
    status: text('status', { enum: ['Actief', 'Geannuleerd', 'Inactief', 'Bevestigd'] })
      .notNull()
      .default('Actief'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex('coaches_email_idx').on(columns.email),
    index('coaches_updated_at_idx').on(columns.updatedAt),
    index('coaches_created_at_idx').on(columns.createdAt),
  ],
)

export const medewerkers = sqliteTable(
  'medewerkers',
  {
    id: integer('id').primaryKey(),
    naam: text('naam').notNull(),
    email: text('email').notNull(),
    rol: text('rol').notNull(),
    status: text('status', { enum: ['Actief', 'Geannuleerd', 'Inactief', 'Bevestigd'] })
      .notNull()
      .default('Actief'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex('medewerkers_email_idx').on(columns.email),
    index('medewerkers_updated_at_idx').on(columns.updatedAt),
    index('medewerkers_created_at_idx').on(columns.createdAt),
  ],
)

export const cursussen_beschikbare_momenten = sqliteTable(
  'cursussen_beschikbare_momenten',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    moment: text('moment')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('cursussen_beschikbare_momenten_order_idx').on(columns._order),
    index('cursussen_beschikbare_momenten_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cursussen.id],
      name: 'cursussen_beschikbare_momenten_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const cursussen = sqliteTable(
  'cursussen',
  {
    id: integer('id').primaryKey(),
    naam: text('naam').notNull(),
    status: text('status', { enum: ['Actief', 'Geannuleerd', 'Inactief', 'Bevestigd'] })
      .notNull()
      .default('Actief'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('cursussen_updated_at_idx').on(columns.updatedAt),
    index('cursussen_created_at_idx').on(columns.createdAt),
  ],
)

export const cursus_inschrijvingen = sqliteTable(
  'cursus_inschrijvingen',
  {
    id: integer('id').primaryKey(),
    lid: integer('lid_id')
      .notNull()
      .references(() => leden.id, {
        onDelete: 'set null',
      }),
    cursus: integer('cursus_id')
      .notNull()
      .references(() => cursussen.id, {
        onDelete: 'set null',
      }),
    moment: text('moment')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    inschrijfDatum: text('inschrijf_datum')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    status: text('status', { enum: ['Actief', 'Geannuleerd', 'Inactief', 'Bevestigd'] })
      .notNull()
      .default('Bevestigd'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('cursus_inschrijvingen_lid_idx').on(columns.lid),
    index('cursus_inschrijvingen_cursus_idx').on(columns.cursus),
    index('cursus_inschrijvingen_updated_at_idx').on(columns.updatedAt),
    index('cursus_inschrijvingen_created_at_idx').on(columns.createdAt),
  ],
)

export const coach_afspraken = sqliteTable(
  'coach_afspraken',
  {
    id: integer('id').primaryKey(),
    lid: integer('lid_id')
      .notNull()
      .references(() => leden.id, {
        onDelete: 'set null',
      }),
    coach: integer('coach_id')
      .notNull()
      .references(() => coaches.id, {
        onDelete: 'set null',
      }),
    datumTijd: text('datum_tijd')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    status: text('status', { enum: ['Actief', 'Geannuleerd', 'Inactief', 'Bevestigd'] })
      .notNull()
      .default('Bevestigd'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('coach_afspraken_lid_idx').on(columns.lid),
    index('coach_afspraken_coach_idx').on(columns.coach),
    index('coach_afspraken_updated_at_idx').on(columns.updatedAt),
    index('coach_afspraken_created_at_idx').on(columns.createdAt),
  ],
)

export const toegangspogingen = sqliteTable(
  'toegangspogingen',
  {
    id: integer('id').primaryKey(),
    lid: integer('lid_id')
      .notNull()
      .references(() => leden.id, {
        onDelete: 'set null',
      }),
    datumTijd: text('datum_tijd')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    resultaat: text('resultaat', { enum: ['Toegestaan', 'Geweigerd'] }).notNull(),
    reden: text('reden').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('toegangspogingen_lid_idx').on(columns.lid),
    index('toegangspogingen_updated_at_idx').on(columns.updatedAt),
    index('toegangspogingen_created_at_idx').on(columns.createdAt),
  ],
)

export const forms_blocks_checkbox = sqliteTable(
  'forms_blocks_checkbox',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    label: text('label'),
    width: numeric('width', { mode: 'number' }),
    required: integer('required', { mode: 'boolean' }),
    defaultValue: integer('default_value', { mode: 'boolean' }),
    blockName: text('block_name'),
  },
  (columns) => [
    index('forms_blocks_checkbox_order_idx').on(columns._order),
    index('forms_blocks_checkbox_parent_id_idx').on(columns._parentID),
    index('forms_blocks_checkbox_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_checkbox_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_country = sqliteTable(
  'forms_blocks_country',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    label: text('label'),
    width: numeric('width', { mode: 'number' }),
    required: integer('required', { mode: 'boolean' }),
    blockName: text('block_name'),
  },
  (columns) => [
    index('forms_blocks_country_order_idx').on(columns._order),
    index('forms_blocks_country_parent_id_idx').on(columns._parentID),
    index('forms_blocks_country_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_country_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_email = sqliteTable(
  'forms_blocks_email',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    label: text('label'),
    width: numeric('width', { mode: 'number' }),
    required: integer('required', { mode: 'boolean' }),
    blockName: text('block_name'),
  },
  (columns) => [
    index('forms_blocks_email_order_idx').on(columns._order),
    index('forms_blocks_email_parent_id_idx').on(columns._parentID),
    index('forms_blocks_email_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_email_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_message = sqliteTable(
  'forms_blocks_message',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    message: text('message', { mode: 'json' }),
    blockName: text('block_name'),
  },
  (columns) => [
    index('forms_blocks_message_order_idx').on(columns._order),
    index('forms_blocks_message_parent_id_idx').on(columns._parentID),
    index('forms_blocks_message_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_message_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_number = sqliteTable(
  'forms_blocks_number',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    label: text('label'),
    width: numeric('width', { mode: 'number' }),
    defaultValue: numeric('default_value', { mode: 'number' }),
    required: integer('required', { mode: 'boolean' }),
    blockName: text('block_name'),
  },
  (columns) => [
    index('forms_blocks_number_order_idx').on(columns._order),
    index('forms_blocks_number_parent_id_idx').on(columns._parentID),
    index('forms_blocks_number_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_number_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_select_options = sqliteTable(
  'forms_blocks_select_options',
  {
    _order: integer('_order').notNull(),
    _parentID: text('_parent_id').notNull(),
    id: text('id').primaryKey(),
    label: text('label').notNull(),
    value: text('value').notNull(),
  },
  (columns) => [
    index('forms_blocks_select_options_order_idx').on(columns._order),
    index('forms_blocks_select_options_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms_blocks_select.id],
      name: 'forms_blocks_select_options_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_select = sqliteTable(
  'forms_blocks_select',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    label: text('label'),
    width: numeric('width', { mode: 'number' }),
    defaultValue: text('default_value'),
    placeholder: text('placeholder'),
    required: integer('required', { mode: 'boolean' }),
    blockName: text('block_name'),
  },
  (columns) => [
    index('forms_blocks_select_order_idx').on(columns._order),
    index('forms_blocks_select_parent_id_idx').on(columns._parentID),
    index('forms_blocks_select_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_select_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_state = sqliteTable(
  'forms_blocks_state',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    label: text('label'),
    width: numeric('width', { mode: 'number' }),
    required: integer('required', { mode: 'boolean' }),
    blockName: text('block_name'),
  },
  (columns) => [
    index('forms_blocks_state_order_idx').on(columns._order),
    index('forms_blocks_state_parent_id_idx').on(columns._parentID),
    index('forms_blocks_state_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_state_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_text = sqliteTable(
  'forms_blocks_text',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    label: text('label'),
    width: numeric('width', { mode: 'number' }),
    defaultValue: text('default_value'),
    required: integer('required', { mode: 'boolean' }),
    blockName: text('block_name'),
  },
  (columns) => [
    index('forms_blocks_text_order_idx').on(columns._order),
    index('forms_blocks_text_parent_id_idx').on(columns._parentID),
    index('forms_blocks_text_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_text_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_textarea = sqliteTable(
  'forms_blocks_textarea',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    label: text('label'),
    width: numeric('width', { mode: 'number' }),
    defaultValue: text('default_value'),
    required: integer('required', { mode: 'boolean' }),
    blockName: text('block_name'),
  },
  (columns) => [
    index('forms_blocks_textarea_order_idx').on(columns._order),
    index('forms_blocks_textarea_parent_id_idx').on(columns._parentID),
    index('forms_blocks_textarea_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_textarea_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_emails = sqliteTable(
  'forms_emails',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    emailTo: text('email_to'),
    cc: text('cc'),
    bcc: text('bcc'),
    replyTo: text('reply_to'),
    emailFrom: text('email_from'),
    subject: text('subject').notNull().default("You've received a new message."),
    message: text('message', { mode: 'json' }),
  },
  (columns) => [
    index('forms_emails_order_idx').on(columns._order),
    index('forms_emails_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_emails_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms = sqliteTable(
  'forms',
  {
    id: integer('id').primaryKey(),
    title: text('title').notNull(),
    submitButtonLabel: text('submit_button_label'),
    confirmationType: text('confirmation_type', { enum: ['message', 'redirect'] }).default(
      'message',
    ),
    confirmationMessage: text('confirmation_message', { mode: 'json' }),
    redirect_url: text('redirect_url'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('forms_updated_at_idx').on(columns.updatedAt),
    index('forms_created_at_idx').on(columns.createdAt),
  ],
)

export const form_submissions_submission_data = sqliteTable(
  'form_submissions_submission_data',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    field: text('field').notNull(),
    value: text('value').notNull(),
  },
  (columns) => [
    index('form_submissions_submission_data_order_idx').on(columns._order),
    index('form_submissions_submission_data_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [form_submissions.id],
      name: 'form_submissions_submission_data_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const form_submissions = sqliteTable(
  'form_submissions',
  {
    id: integer('id').primaryKey(),
    form: integer('form_id')
      .notNull()
      .references(() => forms.id, {
        onDelete: 'set null',
      }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('form_submissions_form_idx').on(columns.form),
    index('form_submissions_updated_at_idx').on(columns.updatedAt),
    index('form_submissions_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = sqliteTable(
  'payload_kv',
  {
    id: integer('id').primaryKey(),
    key: text('key').notNull(),
    data: text('data', { mode: 'json' }).notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_folders_folder_type = sqliteTable(
  'payload_folders_folder_type',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: text('value', { enum: ['media'] }),
    id: integer('id').primaryKey(),
  },
  (columns) => [
    index('payload_folders_folder_type_order_idx').on(columns.order),
    index('payload_folders_folder_type_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_folders.id],
      name: 'payload_folders_folder_type_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_folders = sqliteTable(
  'payload_folders',
  {
    id: integer('id').primaryKey(),
    name: text('name').notNull(),
    folder: integer('folder_id').references((): AnySQLiteColumn => payload_folders.id, {
      onDelete: 'set null',
    }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_folders_name_idx').on(columns.name),
    index('payload_folders_folder_idx').on(columns.folder),
    index('payload_folders_updated_at_idx').on(columns.updatedAt),
    index('payload_folders_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents = sqliteTable(
  'payload_locked_documents',
  {
    id: integer('id').primaryKey(),
    globalSlug: text('global_slug'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = sqliteTable(
  'payload_locked_documents_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    ledenID: integer('leden_id'),
    abonnementenID: integer('abonnementen_id'),
    coachesID: integer('coaches_id'),
    medewerkersID: integer('medewerkers_id'),
    cursussenID: integer('cursussen_id'),
    'cursus-inschrijvingenID': integer('cursus_inschrijvingen_id'),
    'coach-afsprakenID': integer('coach_afspraken_id'),
    toegangspogingenID: integer('toegangspogingen_id'),
    formsID: integer('forms_id'),
    'form-submissionsID': integer('form_submissions_id'),
    'payload-foldersID': integer('payload_folders_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_leden_id_idx').on(columns.ledenID),
    index('payload_locked_documents_rels_abonnementen_id_idx').on(columns.abonnementenID),
    index('payload_locked_documents_rels_coaches_id_idx').on(columns.coachesID),
    index('payload_locked_documents_rels_medewerkers_id_idx').on(columns.medewerkersID),
    index('payload_locked_documents_rels_cursussen_id_idx').on(columns.cursussenID),
    index('payload_locked_documents_rels_cursus_inschrijvingen_id_idx').on(
      columns['cursus-inschrijvingenID'],
    ),
    index('payload_locked_documents_rels_coach_afspraken_id_idx').on(columns['coach-afsprakenID']),
    index('payload_locked_documents_rels_toegangspogingen_id_idx').on(columns.toegangspogingenID),
    index('payload_locked_documents_rels_forms_id_idx').on(columns.formsID),
    index('payload_locked_documents_rels_form_submissions_id_idx').on(
      columns['form-submissionsID'],
    ),
    index('payload_locked_documents_rels_payload_folders_id_idx').on(columns['payload-foldersID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['ledenID']],
      foreignColumns: [leden.id],
      name: 'payload_locked_documents_rels_leden_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['abonnementenID']],
      foreignColumns: [abonnementen.id],
      name: 'payload_locked_documents_rels_abonnementen_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['coachesID']],
      foreignColumns: [coaches.id],
      name: 'payload_locked_documents_rels_coaches_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['medewerkersID']],
      foreignColumns: [medewerkers.id],
      name: 'payload_locked_documents_rels_medewerkers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['cursussenID']],
      foreignColumns: [cursussen.id],
      name: 'payload_locked_documents_rels_cursussen_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['cursus-inschrijvingenID']],
      foreignColumns: [cursus_inschrijvingen.id],
      name: 'payload_locked_documents_rels_cursus_inschrijvingen_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['coach-afsprakenID']],
      foreignColumns: [coach_afspraken.id],
      name: 'payload_locked_documents_rels_coach_afspraken_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['toegangspogingenID']],
      foreignColumns: [toegangspogingen.id],
      name: 'payload_locked_documents_rels_toegangspogingen_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['formsID']],
      foreignColumns: [forms.id],
      name: 'payload_locked_documents_rels_forms_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['form-submissionsID']],
      foreignColumns: [form_submissions.id],
      name: 'payload_locked_documents_rels_form_submissions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['payload-foldersID']],
      foreignColumns: [payload_folders.id],
      name: 'payload_locked_documents_rels_payload_folders_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = sqliteTable(
  'payload_preferences',
  {
    id: integer('id').primaryKey(),
    key: text('key'),
    value: text('value', { mode: 'json' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = sqliteTable(
  'payload_preferences_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = sqliteTable(
  'payload_migrations',
  {
    id: integer('id').primaryKey(),
    name: text('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  lid: one(leden, {
    fields: [users.lid],
    references: [leden.id],
    relationName: 'lid',
  }),
  medewerker: one(medewerkers, {
    fields: [users.medewerker],
    references: [medewerkers.id],
    relationName: 'medewerker',
  }),
  coach: one(coaches, {
    fields: [users.coach],
    references: [coaches.id],
    relationName: 'coach',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, ({ one }) => ({
  folder: one(payload_folders, {
    fields: [media.folder],
    references: [payload_folders.id],
    relationName: 'folder',
  }),
}))
export const relations_leden = relations(leden, ({ one }) => ({
  abonnement: one(abonnementen, {
    fields: [leden.abonnement],
    references: [abonnementen.id],
    relationName: 'abonnement',
  }),
}))
export const relations_abonnementen = relations(abonnementen, () => ({}))
export const relations_coaches = relations(coaches, () => ({}))
export const relations_medewerkers = relations(medewerkers, () => ({}))
export const relations_cursussen_beschikbare_momenten = relations(
  cursussen_beschikbare_momenten,
  ({ one }) => ({
    _parentID: one(cursussen, {
      fields: [cursussen_beschikbare_momenten._parentID],
      references: [cursussen.id],
      relationName: 'beschikbareMomenten',
    }),
  }),
)
export const relations_cursussen = relations(cursussen, ({ many }) => ({
  beschikbareMomenten: many(cursussen_beschikbare_momenten, {
    relationName: 'beschikbareMomenten',
  }),
}))
export const relations_cursus_inschrijvingen = relations(cursus_inschrijvingen, ({ one }) => ({
  lid: one(leden, {
    fields: [cursus_inschrijvingen.lid],
    references: [leden.id],
    relationName: 'lid',
  }),
  cursus: one(cursussen, {
    fields: [cursus_inschrijvingen.cursus],
    references: [cursussen.id],
    relationName: 'cursus',
  }),
}))
export const relations_coach_afspraken = relations(coach_afspraken, ({ one }) => ({
  lid: one(leden, {
    fields: [coach_afspraken.lid],
    references: [leden.id],
    relationName: 'lid',
  }),
  coach: one(coaches, {
    fields: [coach_afspraken.coach],
    references: [coaches.id],
    relationName: 'coach',
  }),
}))
export const relations_toegangspogingen = relations(toegangspogingen, ({ one }) => ({
  lid: one(leden, {
    fields: [toegangspogingen.lid],
    references: [leden.id],
    relationName: 'lid',
  }),
}))
export const relations_forms_blocks_checkbox = relations(forms_blocks_checkbox, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_checkbox._parentID],
    references: [forms.id],
    relationName: '_blocks_checkbox',
  }),
}))
export const relations_forms_blocks_country = relations(forms_blocks_country, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_country._parentID],
    references: [forms.id],
    relationName: '_blocks_country',
  }),
}))
export const relations_forms_blocks_email = relations(forms_blocks_email, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_email._parentID],
    references: [forms.id],
    relationName: '_blocks_email',
  }),
}))
export const relations_forms_blocks_message = relations(forms_blocks_message, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_message._parentID],
    references: [forms.id],
    relationName: '_blocks_message',
  }),
}))
export const relations_forms_blocks_number = relations(forms_blocks_number, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_number._parentID],
    references: [forms.id],
    relationName: '_blocks_number',
  }),
}))
export const relations_forms_blocks_select_options = relations(
  forms_blocks_select_options,
  ({ one }) => ({
    _parentID: one(forms_blocks_select, {
      fields: [forms_blocks_select_options._parentID],
      references: [forms_blocks_select.id],
      relationName: 'options',
    }),
  }),
)
export const relations_forms_blocks_select = relations(forms_blocks_select, ({ one, many }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_select._parentID],
    references: [forms.id],
    relationName: '_blocks_select',
  }),
  options: many(forms_blocks_select_options, {
    relationName: 'options',
  }),
}))
export const relations_forms_blocks_state = relations(forms_blocks_state, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_state._parentID],
    references: [forms.id],
    relationName: '_blocks_state',
  }),
}))
export const relations_forms_blocks_text = relations(forms_blocks_text, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_text._parentID],
    references: [forms.id],
    relationName: '_blocks_text',
  }),
}))
export const relations_forms_blocks_textarea = relations(forms_blocks_textarea, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_textarea._parentID],
    references: [forms.id],
    relationName: '_blocks_textarea',
  }),
}))
export const relations_forms_emails = relations(forms_emails, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_emails._parentID],
    references: [forms.id],
    relationName: 'emails',
  }),
}))
export const relations_forms = relations(forms, ({ many }) => ({
  _blocks_checkbox: many(forms_blocks_checkbox, {
    relationName: '_blocks_checkbox',
  }),
  _blocks_country: many(forms_blocks_country, {
    relationName: '_blocks_country',
  }),
  _blocks_email: many(forms_blocks_email, {
    relationName: '_blocks_email',
  }),
  _blocks_message: many(forms_blocks_message, {
    relationName: '_blocks_message',
  }),
  _blocks_number: many(forms_blocks_number, {
    relationName: '_blocks_number',
  }),
  _blocks_select: many(forms_blocks_select, {
    relationName: '_blocks_select',
  }),
  _blocks_state: many(forms_blocks_state, {
    relationName: '_blocks_state',
  }),
  _blocks_text: many(forms_blocks_text, {
    relationName: '_blocks_text',
  }),
  _blocks_textarea: many(forms_blocks_textarea, {
    relationName: '_blocks_textarea',
  }),
  emails: many(forms_emails, {
    relationName: 'emails',
  }),
}))
export const relations_form_submissions_submission_data = relations(
  form_submissions_submission_data,
  ({ one }) => ({
    _parentID: one(form_submissions, {
      fields: [form_submissions_submission_data._parentID],
      references: [form_submissions.id],
      relationName: 'submissionData',
    }),
  }),
)
export const relations_form_submissions = relations(form_submissions, ({ one, many }) => ({
  form: one(forms, {
    fields: [form_submissions.form],
    references: [forms.id],
    relationName: 'form',
  }),
  submissionData: many(form_submissions_submission_data, {
    relationName: 'submissionData',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_folders_folder_type = relations(
  payload_folders_folder_type,
  ({ one }) => ({
    parent: one(payload_folders, {
      fields: [payload_folders_folder_type.parent],
      references: [payload_folders.id],
      relationName: 'folderType',
    }),
  }),
)
export const relations_payload_folders = relations(payload_folders, ({ one, many }) => ({
  folder: one(payload_folders, {
    fields: [payload_folders.folder],
    references: [payload_folders.id],
    relationName: 'folder',
  }),
  folderType: many(payload_folders_folder_type, {
    relationName: 'folderType',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    ledenID: one(leden, {
      fields: [payload_locked_documents_rels.ledenID],
      references: [leden.id],
      relationName: 'leden',
    }),
    abonnementenID: one(abonnementen, {
      fields: [payload_locked_documents_rels.abonnementenID],
      references: [abonnementen.id],
      relationName: 'abonnementen',
    }),
    coachesID: one(coaches, {
      fields: [payload_locked_documents_rels.coachesID],
      references: [coaches.id],
      relationName: 'coaches',
    }),
    medewerkersID: one(medewerkers, {
      fields: [payload_locked_documents_rels.medewerkersID],
      references: [medewerkers.id],
      relationName: 'medewerkers',
    }),
    cursussenID: one(cursussen, {
      fields: [payload_locked_documents_rels.cursussenID],
      references: [cursussen.id],
      relationName: 'cursussen',
    }),
    'cursus-inschrijvingenID': one(cursus_inschrijvingen, {
      fields: [payload_locked_documents_rels['cursus-inschrijvingenID']],
      references: [cursus_inschrijvingen.id],
      relationName: 'cursus-inschrijvingen',
    }),
    'coach-afsprakenID': one(coach_afspraken, {
      fields: [payload_locked_documents_rels['coach-afsprakenID']],
      references: [coach_afspraken.id],
      relationName: 'coach-afspraken',
    }),
    toegangspogingenID: one(toegangspogingen, {
      fields: [payload_locked_documents_rels.toegangspogingenID],
      references: [toegangspogingen.id],
      relationName: 'toegangspogingen',
    }),
    formsID: one(forms, {
      fields: [payload_locked_documents_rels.formsID],
      references: [forms.id],
      relationName: 'forms',
    }),
    'form-submissionsID': one(form_submissions, {
      fields: [payload_locked_documents_rels['form-submissionsID']],
      references: [form_submissions.id],
      relationName: 'form-submissions',
    }),
    'payload-foldersID': one(payload_folders, {
      fields: [payload_locked_documents_rels['payload-foldersID']],
      references: [payload_folders.id],
      relationName: 'payload-folders',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  leden: typeof leden
  abonnementen: typeof abonnementen
  coaches: typeof coaches
  medewerkers: typeof medewerkers
  cursussen_beschikbare_momenten: typeof cursussen_beschikbare_momenten
  cursussen: typeof cursussen
  cursus_inschrijvingen: typeof cursus_inschrijvingen
  coach_afspraken: typeof coach_afspraken
  toegangspogingen: typeof toegangspogingen
  forms_blocks_checkbox: typeof forms_blocks_checkbox
  forms_blocks_country: typeof forms_blocks_country
  forms_blocks_email: typeof forms_blocks_email
  forms_blocks_message: typeof forms_blocks_message
  forms_blocks_number: typeof forms_blocks_number
  forms_blocks_select_options: typeof forms_blocks_select_options
  forms_blocks_select: typeof forms_blocks_select
  forms_blocks_state: typeof forms_blocks_state
  forms_blocks_text: typeof forms_blocks_text
  forms_blocks_textarea: typeof forms_blocks_textarea
  forms_emails: typeof forms_emails
  forms: typeof forms
  form_submissions_submission_data: typeof form_submissions_submission_data
  form_submissions: typeof form_submissions
  payload_kv: typeof payload_kv
  payload_folders_folder_type: typeof payload_folders_folder_type
  payload_folders: typeof payload_folders
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_leden: typeof relations_leden
  relations_abonnementen: typeof relations_abonnementen
  relations_coaches: typeof relations_coaches
  relations_medewerkers: typeof relations_medewerkers
  relations_cursussen_beschikbare_momenten: typeof relations_cursussen_beschikbare_momenten
  relations_cursussen: typeof relations_cursussen
  relations_cursus_inschrijvingen: typeof relations_cursus_inschrijvingen
  relations_coach_afspraken: typeof relations_coach_afspraken
  relations_toegangspogingen: typeof relations_toegangspogingen
  relations_forms_blocks_checkbox: typeof relations_forms_blocks_checkbox
  relations_forms_blocks_country: typeof relations_forms_blocks_country
  relations_forms_blocks_email: typeof relations_forms_blocks_email
  relations_forms_blocks_message: typeof relations_forms_blocks_message
  relations_forms_blocks_number: typeof relations_forms_blocks_number
  relations_forms_blocks_select_options: typeof relations_forms_blocks_select_options
  relations_forms_blocks_select: typeof relations_forms_blocks_select
  relations_forms_blocks_state: typeof relations_forms_blocks_state
  relations_forms_blocks_text: typeof relations_forms_blocks_text
  relations_forms_blocks_textarea: typeof relations_forms_blocks_textarea
  relations_forms_emails: typeof relations_forms_emails
  relations_forms: typeof relations_forms
  relations_form_submissions_submission_data: typeof relations_form_submissions_submission_data
  relations_form_submissions: typeof relations_form_submissions
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_folders_folder_type: typeof relations_payload_folders_folder_type
  relations_payload_folders: typeof relations_payload_folders
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-sqlite' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
